### ISSUE TITLE
Specific components for BP variant-dependent parts, for preparing assembly files

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/ut_tools#15]
- RB: `DNI` (do not install) on Alpha; `R0402_100R_1%_0.1W_100PPM_50V` on Beta and Gamma
 - RBSP: `DNI` on Alpha and Beta; `R0402_100R_1%_0.1W_100PPM_50V` on Gamma
 - CxRB: `CC0402_47NF_16V_10%_X7R` on Alpha; `R0402_100R_1%_0.1W_100PPM_50V` on Beta and Gamma

**Comment by yipengsun** [comment]
I have finished generating these files. Please take a look at them in the latest release, and see if they satisfy our requirements.
